---
title: "L'imparfait--sortir/partir"
---

<p align=left><font face="Garamond" size="4">Conjuguez les verbes entre 
   parenthèses à l'imparfait.<br>
   Cliquez "C" --&gt; correction.<br>
   Correct? --&gt; *astérisques*. <br>
   Incorrect?--&gt; ====.<br>
   </font>
</p>
<form action="" method=post>
   <font face="Garamond" size="4">Quand j'étais à l'université, j'ai 
   passé une année à Paris. Avec mes amis, nous (sortir) 
   <input size=9 name=item1>
   <input onClick="dasher(form.item1, 'sortions')" type=button value=C name=Button>
   souvent pour danser, mais ils n'aimaient pas le cinéma, alors je 
   (sortir) 
   <input size=9 name=item2>
   <input onClick="dasher(form.item2, 'sortais')" type=button value=C name=Button>
   seul si je voulais voir un film. Je (partir au négatif) 
   <input size=15 
      name=item3>
   <input onClick="dasher(form.item3, 'ne partais pas')" type=button value=C name=Button>
   souvent, mais de temps en temps je (partir) 
   <input size=9 name=item4>
   <input onClick="dasher(form.item4, 'partais')" type=button value=C name=Button>
   en vacances, et parfois les autres (partir) 
   <input size=9 name=item5>
   <input onClick="dasher(form.item5, 'partaient')" type=button value=C name=Button>
   avec moi. <br>
   Et toi Richard, tu (sortir) 
   <input size=9 name=item6>
   <input onClick="dasher(form.item6, 'sortais')" type=button value=C name=Button>
   souvent quand tu étais à Paris? Tu (partir) 
   <input size=9 name=item7>
   <input onClick="dasher(form.item7, 'partais')" type=button value=C name=Button>
   souvent en vacances? Avec tes amis, vous (partir) 
   <input size=9 
      name=item8>
   <input onClick="dasher(form.item8, 'partiez')" type=button value=C name=Button>
   visiter toutes les villes d'Europe? <br>
   <br>
   <br>
   <input onClick="form.item1.value='sortions';form.item2.value='sortais';form.item3.value='ne partais pas';form.item4.value='partais';form.item5.value='partaient';form.item6.value='sortais';form.item7.value='partais';form.item8.value='partiez';" type=button value="Réponses" name=Button>
   <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';" type=button value="Effacer" name=Button>
   </font> 
</form>
<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>