---
title: "L'imparfait--être"
---

<p align=left><font face="Garamond" size="4">Conjuguez le verbe "être" à 
        l'imparfait.<br>
        Cliquez "C" --&gt; correction.<br>
        Correct? --&gt; *astérisques*. <br>
        Incorrect?--&gt; ====.</font><font face="Garamond" size="4"><br>
        </font> </p>

 <form action="" method=post>
              <font face="Garamond" size="4">Salut Michel! Pourquoi est-ce que 
              tu (négatif) 
              <input size=9 name=item1>
              <input onClick="dasher(form.item1, 'n\'étais pas')" type=button value=C name=Button>
              à la fête hier?C' 
              <input size=9 name=item2>
              <input onClick="dasher(form.item2, 'était')" type=button value=C name=Button>
              super! Tout le monde 
              <input size=9 name=item3>
              <input onClick="dasher(form.item3, 'était')" type=button value=C name=Button>
              là (sauf toi, bien sûr). Ah oui, toi et Murielle, vous 
              <input size=9 
      name=item4>
              <input onClick="dasher(form.item4, 'étiez')" type=button value=C name=Button>
              trop paresseux tous les deux. En tout cas, la décoration 
              <input size=9 
      name=item5>
              <input onClick="dasher(form.item5, 'était')" type=button value=C name=Button>
              super bien faite, et Sylvie et Martin 
              <input size=9 name=item6>
              <input onClick="dasher(form.item6, 'étaient')" type=button value=C name=Button>
              en pleine forme. Oui, les Dupont et les Dugros 
              <input size=9 name=item7>
              <input onClick="dasher(form.item7, 'étaient')" type=button value=C name=Button>
              là. Tu aurais dû voir la coiffure de Véronique Dugros--c' 
              <input size=9 
      name=item8>
              <input onClick="dasher(form.item8, 'était')" type=button value=C name=Button>
              trop tendance! Les mèches 
              <input size=9 name=item9>
              <input onClick="dasher(form.item9, 'étaient')" type=button value=C name=Button>
              violettes, et le centre 
              <input size=9 name=item10>
              <input onClick="dasher(form.item10, 'était')" type=button value=C name=Button>
              verdâtre. Nous 
              <input size=9 name=item11>
              <input onClick="dasher(form.item11, 'étions')" type=button value=C name=Button>
              sidérés! Trop génial, quoi! Alors, pourquoi tu n'es pas venu? Tu 
              <input 
      size=9 name=item12>
              <input onClick="dasher(form.item12, 'étais')" type=button value=C name=Button>
              trop fatigué, ou quoi? On 
              <input size=9 name=item13>
              <input onClick="dasher(form.item13, 'était')" type=button value=C name=Button>
              trop déçu de ne pas te voir. <br>
              <br>
              <br>
              <input onClick="form.item1.value='n\'étais pas';form.item2.value='était';form.item3.value='était';form.item4.value='étiez';form.item5.value='était';form.item6.value='étaient';form.item7.value='étaient';form.item8.value='était';form.item9.value='étaient';form.item10.value='était';form.item11.value='étions';form.item12.value='étais';form.item13.value='était';" type=button value="Réponses" name=Button>
              <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';form.item9.value='';form.item10.value='';form.item11.value='';form.item12.value='';form.item13.value='';" type=button value="Effacer" name=Button>
              </font> 
            </form>

<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>