---
title: "L'imparfait (2)"
---

N'oubliez pas; l'imparfait s'emploie pour exprimer<br />
--une description, un état d'esprit, de santé, la météo [HOW THINGS WERE]<br />
--une habitude [SOMETHING THAT USED TO HAPPEN]<br />
--une action en cours de déroulement [SOMETHING THAT WAS HAPPENING]<br />
--une hypothèse irréelle [IF SOMETHING DID HAPPEN]  <br />
--une suggestion [WHY DON'T WE DO SOMETHING]

<body>
<table width="100%" border="0" bgcolor="#FFFFFF" align="center" cellpadding="20">
  <tr> 
    <td align="left" valign="top"> 
     
      <p><font face="Garamond" size="4">Cliquez &quot;Suite&quot; pour voir la 
        premi&egrave;re question.</font></p>
      <p><font face="Garamond" size="4">Complétez les phrases en utilisant l'imparfait. 
        <br> Modèle: Si nous…. [hypothèse irréelle] --> Si nous étions plus riches, nous achèterions un bateau.<br>

        Cliquez &quot;Montrer&quot; pour comparer votre r&eacute;ponse &agrave; 
        la r&eacute;ponse du professeur. Toutes les réponses seront différentes; ce qui est important ici, c'est de comprendre l'esprit de la phrase et de l'emploi de l'imparfait.<br>
        Cliquez &quot;Cacher&quot; pour faire dispara&icirc;tre la r&eacute;ponse 
        du professeur. </font></p>

      <p><font face="Garamond" size="4">Cliquez Suite/Retour pour voir les autres 
        questions.<br>
        </font></p>
      <table width="80%" border=0 align="center">
        <tbody> 
        <tr> 
          <td width=395> 
            <p> 
            <form name=qbox action="" method=post>
              <p><font face="Garamond" size="4"><b>Question<br>
                </b> 
                <textarea name=q rows=3 wrap=virtual cols=50></textarea>

                <br>
                </font></p>
              <center>
                <div align=left> <font face="Garamond" size="4"> 
                  <input onClick=begin(-1) type=button value="&lt;=Retour" name=show>
                  &nbsp; &nbsp; 
                  <input onClick=begin(1) type=button value="Suite=&gt;" name=show>
                  <br>
                  </font></div>

              </center>
            </form>
            <p></p>
            <p></p>
          </td>
          <td width=200></td>
        </tr>
        </tbody> 
      </table>

      <table width="80%" border=0 align="center">
        <tbody> 
        <tr> 
          <td valign=top width=236> 
            <p><font face="Garamond" size="4"><b>Votre réponse</b> </font> 
            <form name=Sinput action="" method=post>
              <p> <font face="Garamond" size="4"> 
                <textarea name=Content rows=4 wrap=virtual cols=35></textarea>
                </font> 
            </form>

            <p></p>
            <p></p>
          </td>
          <td valign=top width=308> 
            <p><font face="Garamond" size="4"><b>Réponse du professeur</b> </font> 
            <form name=feedback action="" method=post>
              <p> <font face="Garamond" size="4"> 
                <textarea name=fb rows=4 wrap=virtual cols=35></textarea>

                </font> 
            </form>
            <form name=check action="" method=post>
              <center>
                <div align=left> <font face="Garamond" size="4"> 
                  <input onClick=Check() type=button value="Montrer" name=Button>
                  <input onClick="(document.feedback.fb.value='')" type=button value="Cacher" name=show>
                  </font></div>
              </center>

            </form>
            <p></p>
          </td>
        </tr>
        </tbody> 
      </table>
      <div align="center"></div>
      <p>&nbsp;</p>
      </td>

  </tr>
</table>
<p>&nbsp;</p>
</body>
<HEAD>
<META http-equiv=Content-Type content="text/html; charset=windows-1252">
<SCRIPT language=Javascript><!--//
//  This code is based on a script by Marmoe Soemarmo.  
//  Dan Beeby modified it and wrote the creation interface, JavaScripts, and Perl Scripts.
//  http://lang.swarthmore.edu/mellon -- dbeeby@haverford.edu.
//  Content by Alison Murray Levine, University of Virginia -- alevine@virginia.edu.
//  You may borrow and modify these scripts, but please give credit where credit is due.
	var Question= new Array();
	var Answer= new Array();
//---------------------DATA--------------------

Question[1]="Quand j'étais au lycée, nous… [habitude]";Question[2]="Quand je suis arrivée à Dakar, il… [description de la météo]";Question[3]="Quand le président a été élu, [description de l'état des choses dans le pays]";Question[4]="Si nous… [hypothèse irréelle]";Question[5]="Si nous… [suggestion]";Question[6]="Aujourd'hui, ça va mieux, mais hier… [description d'un état de santé]";Question[7]="Si tu… [hypothèse irréelle]";Question[8]="Le message est arrivé juste au moment où je [action en cours de déroulement]";Question[9]="Si vous… [suggestion]";Question[10]="A l'époque, nous… [habitude]";

Answer[1]="Quand j'étais au lycée, nous nous écrivions de petits mots en classe.";Answer[2]="Quand je suis arrivée à Dakar, il faisait beau et chaud.";Answer[3]="Quand le président a été élu, il y avait une crise économique grave dans le pays.";Answer[4]="Si nous avions plus de chance, nous aurions plus d'argent.";Answer[5]="Si nous allions à San Francisco ce week-end ?";Answer[6]="Aujourd'hui, ça va mieux, mais hier, j'avais mal à la tête et j'avais envie de vomir.";Answer[7]="Si tu travaillais plus, tu aurais de meilleures notes.";Answer[8]="Le message est arrivé juste au moment où j'écrivais à Jean pour lui demander pourquoi il ne m'avait pas répondu.";Answer[9]="Si vous alliez ranger un peu votre chambre avant de jouer dehors ?";Answer[10]="A l'époque, nous allions toujours voir des films sur le grand écran.";

//-------------------END DATA-------------

var NextQ = 0;
var QN = 0;

function begin(QN){
NextQ = NextQ + QN
	if (Question[NextQ] == null) {
alert("Il n’y a plus de questions. Cliquez sur suite/retour pour revoir les questions.")
	}
	document.feedback.fb.value=""
	document.Sinput.Content.value=""
	document.qbox.q.value=Question[NextQ]
}

function Check(){
	if (document.Sinput.Content.value == ""){
        document.feedback.fb.value="Essayez de répondre à la question avant de voir la réponse du professeur."
        }
	else{
	document.feedback.fb.value=Answer[NextQ]
}
}
//--></SCRIPT>

<META content="MSHTML 6.00.2800.1400" name=GENERATOR>


<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>



