---
title: "How/where/when...(2)"
---
<p align=left><font face="Garamond" size="4">Complétez les phrases en utilisant 
        <strong>où, comment, quand, pourquoi, est-ce que</strong> ou <strong>qu'est-ce que</strong>. 
        <br>
        Cliquez "C" --&gt; correction.<br>
        Correct? --&gt; *astérisques*. <br>
        Incorrect?--&gt; ====.<br>
        </font></p>

<form action="" method=post>
   <font face="Garamond" size="4"> 1. Tu veux aller 
   <input size=15 name=item1>
   <input onClick="dasher(form.item1, 'où')" type=button value=C name=Button>
   ?<br>
   --A Marseille.<br>
   <br>
   2. 
   <input size=15 name=item2>
   <input onClick="dasher(form.item2, 'Est-ce que')" type=button value=C name=Button>
   tu connais Richard?<br>
   --Oui, nous avons fait connaissance à la soirée hier.<br>
   <br>
   3. 
   <input size=15 name=item3>
   <input onClick="dasher(form.item3, 'Pourquoi')" type=button value=C name=Button>
   est-ce que tu vas à Washington?<br>
   --Pour protester la loi contre l'avortement.<br>
   <br>
   4. 
   <input size=15 name=item4>
   <input onClick="dasher(form.item4, 'Qu\'est-ce que')" type=button value=C name=Button>
   vous allez faire? <br>
   --Nous allons dormir sur la plage.<br>
   <br>
   5. Tu t'appelles 
   <input size=15 name=item5>
   <input onClick="dasher(form.item5, 'comment')" type=button value=C name=Button>
   ?<br>
   --Sylvie Martel.<br>
   <br>
   6. 
   <input size=15 name=item6>
   <input onClick="dasher(form.item6, 'Est-ce que')" type=button value=C name=Button>
   tu viens?<br>
   --Oui, oui!<br>
   <br>
   7. 
   <input size=15 name=item7>
   <input onClick="dasher(form.item7, 'Quand')" type=button value=C name=Button>
   est-ce que vous partez?<br>
   Demain après les classes.<br>
   <br>
   8. 
   <input 
      size=15 name=item8>
   <input onClick="dasher(form.item8, 'Comment')" type=button value=C name=Button>
   sont les nouveaux films de Tarantino?<br>
   --Encore plus violents que les autres.<br>
   <br>
   9. 
   <input size=15 name=item9>
   <input onClick="dasher(form.item9, 'Qu\'est-ce que')" type=button value=C name=Button>
   vous faites comme profession?<br>
   --Je suis artiste peintre. <br>
   <br>
   <br>
   <input onClick="form.item1.value='où';form.item2.value='Est-ce que';form.item3.value='Pourquoi';form.item4.value='Qu\'est-ce que';form.item5.value='comment';form.item6.value='Est-ce que';form.item7.value='Quand';form.item8.value='Comment';form.item9.value='Qu\'est-ce que';" type=button value="Réponses" name=Button>
   <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';form.item9.value='';" type=button value="Effacer" name=Button>
   </font> 
</form>

<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>