---
title: "L’entretien d’embauche (transcription)"
---
--Alors...Vous savez taper à la machine?\
--Bien sûr.\
--Vous savez vous servir d'un ordinateur?\
--Ben oui.\
--Vous savez faire des photocopies?\
--Pas de problème, j'en ai déjà fait plein.\
--Est-ce que vous avez déjà travaillé sur des tableurs?\
--Des tableurs...\
--Des tableurs, c'est des feuilles de calcul.\
--Oui bien sûr, des tableurs, plein de fois, et surtout le calcul, je suis...je suis bon, quoi.\
--Quel logiciel?\
--Alors là c'est drôle, j'ai oublié, c'était des logiciels...des trucs... des logiciels...normaux, des logiciels...allemands, peut-être?\
--Je vois que vous n'avez pas travaillé depuis deux ans.\
--Ben, oui.\
--Pourquoi?\
--Pourquoi, parce que j'étais à Fleury.\
--Fleury?\
--J'étais à la centrale, quoi.\
--La centrale de quoi?\
--La centrale des particuliers.\
--J'étais en taule. Vous vous foutez de ma gueule ou quoi là?\
--Ah, vous étiez en prison?\
--Mais ils ne vous ont rien dit à l'agence?\
--Non.\
--OK, ça va aller.\
--Non mais je...