---
title: "Le futur--faire"
---

<p align=left><font face="Garamond" size="4">Conjuguez le verbe *faire* 
        au futur.<br>
        Cliquez "C" --&gt; correction.<br>
        Correct? --&gt; *astérisques*. <br>
        Incorrect?--&gt; ====.</font><font face="Garamond" size="4"><br>
        </font> </p>

 <form action="" method=post>
              <font face="Garamond" size="4"> La météo: Aujourd'hui, il 
              <input size=9 
      name=item1>
              <input onClick="dasher(form.item1, 'fera')" type=button value=C name=Button>
              froid avec un vent léger du sud-ouest. Ce soir, il 
              <input size=9 
      name=item2>
              <input onClick="dasher(form.item2, 'fera')" type=button value=C name=Button>
              très froid, et demain, il 
              <input size=9 name=item3>
              <input onClick="dasher(form.item3, 'fera')" type=button value=C name=Button>
              plus chaud. C'est pour cela qu'aujourd'hui, Jane 
              <input size=9 name=item4>
              <input onClick="dasher(form.item4, 'fera')" type=button value=C name=Button>
              ses devoirs et les autres enfants 
              <input size=9 name=item5>
              <input onClick="dasher(form.item5, 'feront')" type=button value=C name=Button>
              le ménage chez nous. Nous, nous 
              <input size=9 name=item6>
              <input onClick="dasher(form.item6, 'ferons')" type=button value=C name=Button>
              la cuisine et la vaisselle après le repas. Mais personne ne 
              <input size=9 
      name=item7>
              <input onClick="dasher(form.item7, 'fera')" type=button value=C name=Button>
              du ski aujourd'hui. Par contre, demain, Jane 
              <input size=9 name=item8>
              <input onClick="dasher(form.item8, 'fera')" type=button value=C name=Button>
              du ski. Toi Thomas, tu 
              <input size=9 name=item9>
              <input onClick="dasher(form.item9, 'feras')" type=button value=C name=Button>
              du snowboard, n'est-ce pas? Elisabeth et Richard, vous 
              <input size=9 
      name=item10>
              <input onClick="dasher(form.item10, 'ferez')" type=button value=C name=Button>
              de votre mieux de ne pas faire de bêtises, et si vous y arrivez, 
              vous 
              <input size=9 name=item11>
              <input onClick="dasher(form.item11, 'ferez')" type=button value=C name=Button>
              du ski l'après-midi. Nous 
              <input size=9 name=item12>
              <input onClick="dasher(form.item12, 'ferons')" type=button value=C name=Button>
              nos corrections mais nous viendrons avec vous l'après-midi. <br>
              <br>
              <input onClick="form.item1.value='fera';form.item2.value='fera';form.item3.value='fera';form.item4.value='fera';form.item5.value='feront';form.item6.value='ferons';form.item7.value='fera';form.item8.value='fera';form.item9.value='feras';form.item10.value='ferez';form.item11.value='ferez';form.item12.value='ferons';" type=button value="Montrer les r&eacute;ponses" name=Button>
              <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';form.item9.value='';form.item10.value='';form.item11.value='';form.item12.value='';" type=button value="Effacer les r&eacute;ponses" name=Button>
              </font> 
            </form>

<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>