---
title: "Mieux, meilleur..."
---

####La rupture

Traduisez les phrases suivantes, qui décrivent une rupture.<br />
Cliquez &quot;Suite&quot; pour voir la  premi&egrave;re phrase. Ecrivez la traduction, en employant une expression avec *mieux* ou *meilleur* (rien de mieux, faute de mieux, au mieux, il vaut mieux, meilleur marché, etc). <br>
Cliquez &quot;Montrer&quot; pour comparer votre traduction &agrave; la suggestion du professeur.<br>
Cliquez &quot;Cacher&quot; pour faire dispara&icirc;tre la suggestion du professeur. <br />
Cliquez &quot;Suite/Retour&quot; pour voir les autres phrases.<br>

<html>
<head>
  <title>Translation Exercise</title>
</head>
<body>
  <table width="80%" border="0" align="center">
    <tbody>
      <tr>
        <td width="236">
          <form name="qbox" action="" method="post">
            <p><b>Traduisez:</b></p>
            <textarea name="q" rows="3" wrap="virtual" cols="50"></textarea>
            <br>
            <center>
              <div>
                <input type="button" value="&lt;=Retour" name="show" onclick="begin(-1)">
                &nbsp; &nbsp;
                <input type="button" value="Suite=&gt;" name="show" onclick="begin(1)">
              </div>
            </center>
          </form>
          <p></p>
          <p></p>
        </td>
        <td width="200"></td>
      </tr>
    </tbody>
  </table>
  <table width="80%" border="0" align="center">
    <tbody>
      <tr>
        <td valign="top" width="236">
          <p><b>Votre traduction:</b></p>
          <form name="Sinput" action="" method="post">
            <p>
              <textarea name="Content" rows="4" wrap="virtual" cols="35"></textarea>
            </p>
          </form>
          <p></p>
          <p></p>
        </td>
        <td valign="top" width="308">
          <p><b>Le professeur suggère:</b></p>
          <form name="feedback" action="" method="post">
            <p>
              <textarea name="fb" rows="4" wrap="virtual" cols="35"></textarea>
            </p>
          </form>
          <form name="check" action="" method="post">
            <center>
              <div>
                <input type="button" value="Montrer" name="Button" onclick="Check()">
                <input type="button" value="Cacher" name="show" onclick="document.feedback.fb.value=''">
              </div>
            </center>
          </form>
        </td>
      </tr>
    </tbody>
  </table>

  <script>
    // Your JavaScript code here
    var Question = new Array();
    var Answer = new Array();
    // Add your data here
    // ...

    var NextQ = 0;
    var QN = 0;

    function begin(QN) {
      NextQ = NextQ + QN;
      if (Question[NextQ] == null) {
        alert("Il n’y a plus de questions. Cliquez sur suite/retour pour revoir les questions.");
      }
      document.feedback.fb.value = "";
      document.Sinput.Content.value = "";
      document.qbox.q.value = Question[NextQ];
    }

    function Check() {
      if (document.Sinput.Content.value == "") {
        document.feedback.fb.value = "Essayez de répondre à la question avant de voir la réponse du professeur.";
      } else {
        document.feedback.fb.value = Answer[NextQ];
      }
    }
  </script>
</body>
</html>
