---
title: "Le/la vs. un/une (1)"
---

<p align=left><font face="Garamond" size="4">Complétez les phrases en utilisant 
       l'article <strong>défini</strong> (le/la/l') ou <strong>indéfini</strong> (un/une). Cliquez "C" --&gt; correction.<br>
        Correct? --&gt; *astérisques*. <br>
        Incorrect?--&gt; ====. </font></p>

<form action="" method=post>
              <font face="Garamond" size="4"> La Grèce, c'est 
              <input size=9 name=item1>
              <input onClick="dasher(form.item1, 'le')" type=button value=C name=Button>
              pays où ils ont fait toutes leurs études.<br>
              Est-ce qu'il y a 
              <input 
      size=9 name=item2>
              <input onClick="dasher(form.item2, 'une')" type=button value=C name=Button>
              boulangerie dans le quartier?<br>
              À droite, c'est 
              <input size=9 name=item3>
              <input onClick="dasher(form.item3, 'la')" type=button value=C name=Button>
              chambre des enfants. À gauche, 
              <input size=9 name=item4>
              <input onClick="dasher(form.item4, 'le')" type=button value=C name=Button>
              salon. En face, 
              <input size=9 name=item5>
              <input onClick="dasher(form.item5, 'la')" type=button value=C name=Button>
              cuisine. Il y a 
              <input size=9 name=item6>
              <input onClick="dasher(form.item6, 'une')" type=button value=C name=Button>
              salle de bains au rez-de-chaussée et 
              <input size=9 name=item7>
              <input onClick="dasher(form.item7, 'une')" type=button value=C name=Button>
              autre au premier étage.<br>
              Tu connais 
              <input size=9 name=item8>
              <input onClick="dasher(form.item8, 'la')" type=button value=C name=Button>
              grand-mère d'Elisabeth?<br>
              J'habite dans 
              <input size=9 name=item9>
              <input onClick="dasher(form.item9, 'la')" type=button value=C name=Button>
              rue de l'Espérance.<br>
              J'ai réservé 
              <input size=9 name=item10>
              <input onClick="dasher(form.item10, 'une')" type=button value=C name=Button>
              voiture à l'aéroport.<br>
              Voici la carte magnétique qui permet d'ouvrir 
              <input size=9 name=item11>
              <input onClick="dasher(form.item11, 'la')" type=button value=C name=Button>
              chambre. C'est 
              <input size=9 name=item12>
              <input onClick="dasher(form.item12, 'le')" type=button value=C name=Button>
              numéro 13.<br>
              Nous habitons sur 
              <input size=9 name=item13>
              <input onClick="dasher(form.item13, 'la')" type=button value=C name=Button>
              place centrale du village.<br>
              J'aime beaucoup 
              <input size=9 name=item14>
              <input onClick="dasher(form.item14, 'le')" type=button value=C name=Button>
              soleil, 
              <input size=9 name=item15>
              <input onClick="dasher(form.item15, 'la')" type=button value=C name=Button>
              montagne, et 
              <input size=9 name=item16>
              <input onClick="dasher(form.item16, 'la')" type=button value=C name=Button>
              neige.<br>
              Aix-en-Provence, c'est 
              <input size=9 name=item17>
              <input onClick="dasher(form.item17, 'une')" type=button value=C name=Button>
              ville très sympathique. <br>
              <br>
              <br>
              <input onClick="form.item1.value='le';form.item2.value='une';form.item3.value='la';form.item4.value='le';form.item5.value='la';form.item6.value='une';form.item7.value='une';form.item8.value='la';form.item9.value='la';form.item10.value='une';form.item11.value='la';form.item12.value='le';form.item13.value='la';form.item14.value='le';form.item15.value='la';form.item16.value='la';form.item17.value='une';" type=button value="Réponses" name=Button>
              <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';form.item9.value='';form.item10.value='';form.item11.value='';form.item12.value='';form.item13.value='';form.item14.value='';form.item15.value='';form.item16.value='';form.item17.value='';" type=button value="Effacer" name=Button>
              </font> 
            </form>


<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, ajlevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>