---
title: "Le/la vs un/une vs. du/de la (2)"
---
### (articles d&eacute;finis, ind&eacute;finis, partitifs)
Compl&eacute;tez ce texte sur les mus&eacute;es par l'article correct.<br>Cliquez sur "montrer les r&eacute;ponses" pour voir toutes les r&eacute;ponses; vous pouvez ensuite les effacer pour faire l'exercice vous-même. <br />
Cliquez <strong>C</strong> pour voir une correction. Correct? --&gt; *astérisques*.  Incorrect?--&gt; ====.</font><br />Cliquez <strong>?</strong> pour voir un indice (=*a hint*).
<p>RAPPEL: <br>
<strong>Article d&eacute;fini </strong>(le, la, les, l'): [no change after neg. or quantity]=a specific person or thing, OR all the XXX in the world, OR an abstract concept <br>
<strong>Article ind&eacute;fini</strong> (un, une, des): [change to de/d' after neg. or quantity]= one or some countable things among many; "des" is an imprecise quantity <br>
<strong>Article partitif </strong>(du, de la, de l', des): [change to de/d' after neg.  or quantity]= part of a non-countable whole; "des" is an imprecise quantity</p>
### Les musées

<form action="" method="post">
   <p> <font face="Garamond" size="4"> 
      <input size="9" name="item1">
      <input onClick="dasher(form.item1, 'Les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(1, form.feedback1)" type="button" value="?" name="feedback1">
      Am&eacute;ricains aiment 
      <input size="9" name="item2">
      <input onClick="dasher(form.item2, 'les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(2, form.feedback2)" type="button" value="?" name="feedback2">
      mus&eacute;es. &Agrave; Paris, par exemple, il y a 
      <input size="9" name="item3">
      <input onClick="dasher(form.item3, 'le')" type="button" value="C" name="Button">
      <input onClick="show_feedback(3, form.feedback3)" type="button" value="?" name="feedback3">
      Louvre, 
      <input size="9" name="item4">
      <input onClick="dasher(form.item4, 'le')" type="button" value="C" name="Button">
      <input onClick="show_feedback(4, form.feedback4)" type="button" value="?" name="feedback4">
      Mus&eacute;e d'Orsay, et beaucoup 
      <input size="9" name="item5">
      <input onClick="dasher(form.item5, 'de')" type="button" value="C" name="Button">
      <input onClick="show_feedback(5, form.feedback5)" type="button" value="?" name="feedback5">
      petits mus&eacute;es aussi. Aujourd'hui, je visite 
      <input size="9" name="item6">
      <input onClick="dasher(form.item6, 'le')" type="button" value="C" name="Button">
      <input onClick="show_feedback(6, form.feedback6)" type="button" value="?" name="feedback6">
      Mus&eacute;e Rodin &agrave; Paris. 
      <input size="9" name="item7">
      <input onClick="dasher(form.item7, 'Les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(7, form.feedback7)" type="button" value="?" name="feedback7">
      Am&eacute;ricains connaissent bien Rodin. Aujourd'hui, il y a 
      beaucoup 
      <input size="9" name="item8">
      <input onClick="dasher(form.item8, 'd\'')" type="button" value="C" name="Button">
      <input onClick="show_feedback(8, form.feedback8)" type="button" value="?" name="feedback8">
      Am&eacute;ricains qui admirent 
      <input size="9" name="item9">
      <input onClick="dasher(form.item9, 'les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(9, form.feedback9)" type="button" value="?" name="feedback9">
      sculptures et 
      <input size="9" name="item10">
      <input onClick="dasher(form.item10, 'les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(10, form.feedback10)" type="button" value="?" name="feedback10">
      dessins de Rodin qui sont pr&eacute;sent&eacute;s ici. Il y a 
      aussi 
      <input size="9" name="item11">
      <input onClick="dasher(form.item11, 'une')" type="button" value="C" name="Button">
      <input onClick="show_feedback(11, form.feedback11)" type="button" value="?" name="feedback11">
      exposition sp&eacute;ciale o&ugrave; on peut voir 
      <input size="9" name="item12">
      <input onClick="dasher(form.item12, 'des')" type="button" value="C" name="Button">
      <input onClick="show_feedback(12, form.feedback12)" type="button" value="?" name="feedback12">
      sculptures de Camille Claudel. 
      <input size="9" name="item13">
      <input onClick="dasher(form.item13, 'Les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(13, form.feedback13)" type="button" value="?" name="feedback13">
      mus&eacute;es fran&ccedil;ais et 
      <input size="9" name="item14">
      <input onClick="dasher(form.item14, 'les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(14, form.feedback14)" type="button" value="?" name="feedback14">
      mus&eacute;es am&eacute;ricains sont assez semblables. Chaque 
      oeuvre est pr&eacute;sent&eacute;e avec 
      <input size="9" name="item15">
      <input onClick="dasher(form.item15, 'une')" type="button" value="C" name="Button">
      <input onClick="show_feedback(15, form.feedback15)" type="button" value="?" name="feedback15">
      &eacute;tiquette qui identifie 
      <input size="9" name="item16">
      <input onClick="dasher(form.item16, 'l\'')" type="button" value="C" name="Button">
      <input onClick="show_feedback(16, form.feedback16)" type="button" value="?" name="feedback16">
      artiste et 
      <input size="9" name="item17">
      <input onClick="dasher(form.item17, 'la')" type="button" value="C" name="Button">
      <input onClick="show_feedback(17, form.feedback17)" type="button" value="?" name="feedback17">
      date de 
      <input size="9" name="item18">
      <input onClick="dasher(form.item18, 'l\'')" type="button" value="C" name="Button">
      <input onClick="show_feedback(18, form.feedback18)" type="button" value="?" name="feedback18">
      oeuvre. Dans certains mus&eacute;es, il n'y a pas 
      <input size="9" name="item19">
      <input onClick="dasher(form.item19, 'd\'')" type="button" value="C" name="Button">
      <input onClick="show_feedback(19, form.feedback19)" type="button" value="?" name="feedback19">
      &eacute;tiquettes, mais c'est rare. Dans 
      <input size="9" name="item20">
      <input onClick="dasher(form.item20, 'les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(20, form.feedback20)" type="button" value="?" name="feedback20">
      boutiques des mus&eacute;es, 
      <input size="9" name="item21">
      <input onClick="dasher(form.item21, 'les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(21, form.feedback21)" type="button" value="?" name="feedback21">
      touristes d&eacute;pensent souvent beaucoup 
      <input size="9" name="item22">
      <input onClick="dasher(form.item22, 'd\'')" type="button" value="C" name="Button">
      <input onClick="show_feedback(22, form.feedback22)" type="button" value="?" name="feedback22">
      argent. Aujourd'hui au mus&eacute;e Rodin, il y a 
      <input size="9" name="item23">
      <input onClick="dasher(form.item23, 'des')" type="button" value="C" name="Button">
      <input onClick="show_feedback(23, form.feedback23)" type="button" value="?" name="feedback23">
      touristes qui ach&egrave;tent 
      <input size="9" name="item24">
      <input onClick="dasher(form.item24, 'des')" type="button" value="C" name="Button">
      <input onClick="show_feedback(24, form.feedback24)" type="button" value="?" name="feedback24">
      affiches, 
      <input size="9" name="item25">
      <input onClick="dasher(form.item25, 'des')" type="button" value="C" name="Button">
      <input onClick="show_feedback(25, form.feedback25)" type="button" value="?" name="feedback25">
      cartes postales, et parfois 
      <input size="9" name="item26">
      <input onClick="dasher(form.item26, 'de la')" type="button" value="C" name="Button">
      <input onClick="show_feedback(26, form.feedback26)" type="button" value="?" name="feedback26">
      litt&eacute;rature (f.). Je vois une femme l&agrave;-bas, qui 
      ach&egrave;te 
      <input size="9" name="item27">
      <input onClick="dasher(form.item27, 'une')" type="button" value="C" name="Button">
      <input onClick="show_feedback(27, form.feedback27)" type="button" value="?" name="feedback27">
      sculpture originale de Rodin! Mais en g&eacute;n&eacute;ral, 
      <input size="9" name="item28">
      <input onClick="dasher(form.item28, 'les')" type="button" value="C" name="Button">
      <input onClick="show_feedback(28, form.feedback28)" type="button" value="?" name="feedback28">
      Am&eacute;ricains ach&egrave;tent 
      <input size="9" name="item29">
      <input onClick="dasher(form.item29, 'des')" type="button" value="C" name="Button">
      <input onClick="show_feedback(29, form.feedback29)" type="button" value="?" name="feedback29">
      reproductions. Moi, j'ai achet&eacute; 
      <input size="9" name="item30">
      <input onClick="dasher(form.item30, 'une')" type="button" value="C" name="Button">
      <input onClick="show_feedback(30, form.feedback30)" type="button" value="?" name="feedback30">
      affiche de Rodin, et je vais mettre mon affiche dans 
      <input size="9" name="item31">
      <input onClick="dasher(form.item31, 'la')" type="button" value="C" name="Button">
      <input onClick="show_feedback(31, form.feedback31)" type="button" value="?" name="feedback31">
      cuisine de mon nouvel appartement. <br>
      <br>
      <br>
      <input onClick="form.item1.value='Les';form.item2.value='les';form.item3.value='le';form.item4.value='le';form.item5.value='de';form.item6.value='le';form.item7.value='Les';form.item8.value='d\'';form.item9.value='les';form.item10.value='les';form.item11.value='une';form.item12.value='des';form.item13.value='Les';form.item14.value='les';form.item15.value='une';form.item16.value='l\'';form.item17.value='la';form.item18.value='l\'';form.item19.value='d\'';form.item20.value='les';form.item21.value='les';form.item22.value='d\'';form.item23.value='des';form.item24.value='des';form.item25.value='des';form.item26.value='de la';form.item27.value='une';form.item28.value='les';form.item29.value='des';form.item30.value='une';form.item31.value='la';" type="button" value="Réponses" name="Button">
      <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';form.item9.value='';form.item10.value='';form.item11.value='';form.item12.value='';form.item13.value='';form.item14.value='';form.item15.value='';form.item16.value='';form.item17.value='';form.item18.value='';form.item19.value='';form.item20.value='';form.item21.value='';form.item22.value='';form.item23.value='';form.item24.value='';form.item25.value='';form.item26.value='';form.item27.value='';form.item28.value='';form.item29.value='';form.item30.value='';form.item31.value='';" type="button" value="Effacer" name="Button">
      </font>
   </p>
</form>


<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}
function show_feedback(itemno,feedback_input) {

	feedback_input.value=feedback[itemno];
	
}

var feedback=new Array();
feedback[1]='C\'est une généralisation sur les Américains.';
feedback[2]='C\'est une généralisation';
feedback[3]='C\'est un musée spécifique.';
feedback[4]='C\'est un musée spécifique.';
feedback[5]='C\'est une quantité (beaucoup).';
feedback[6]='C\'est un musée spécifique.';
feedback[7]='C\'est une généralisation sur les Américains.';
feedback[8]='C\'est une quantité.';
feedback[9]='Ce sont des objets spécifiques (les objets qui sont dans le musée), pas une généralisation.';
feedback[10]='Ce sont des objets spécifiques (les objets qui sont dans le musée), pas une généralisation.';
feedback[11]='*there\'s the* or *there\'s a*?';
feedback[12]='On ne fait pas une généralisation sur TOUTES les sculptures du monde, on parle d\'un nombre limité.';
feedback[13]='C\'est une généralisation.';
feedback[14]='C\'est une généralisation.';
feedback[15]='On peut compter les étiquettes.';
feedback[16]='C\'est un artiste spécifique.';
feedback[17]='La date est spécifique.';
feedback[18]='L\'oeuvre est spécifique.';
feedback[19]='On parle d\'une quantité, mais il y a un négatif.';
feedback[20]='C\'est une généralisation.';
feedback[21]='C\'est une généralisation.';
feedback[22]='C\'est une quantité.';
feedback[23]='Ce n\'est pas une généralisation, mais une quantité imprécise.';
feedback[24]='Ce n\'est pas une généralisation (on ne peut pas acheter TOUTES les affiches du monde), c\'est une quantité imprécise.';
feedback[25]='Ce n\'est pas une généralisation (on ne peut pas acheter TOUTES les cartes du monde), c\'est une quantité imprécise.';
feedback[26]='Ce n\'est pas une généralisation (on ne peut pas acheter TOUTE la littérature du monde), c\'est une quantité imprécise.';
feedback[27]='C\'est une chose qu\'on peut compter.';
feedback[28]='C\'est une généralisation.';
feedback[29]='Ce n\'est pas une généralisation: impossible d\'acheter TOUTES les reproductions du monde!';
feedback[30]='C\'est une chose, parmi d\'autres, qu\'on peut compter.';
feedback[31]='C\'est une pièce spécifique; il n\'y a pas d\'autres cuisines chez moi.';


<!-- done hiding --></SCRIPT>