---
title: "Plural Forms (1)"
---

Complétez les phrases en utilisant *le,* *la,* ou *les.*\
Cliquez "C" --> correction.\
Correct? --> *astérisques*.\
Incorrect?--> ====.

<form action="" method=post>
   <font face="Garamond" size="4"> 1. Tu as lu 
   <input size=9 name=item1>
   <input onClick="dasher(form.item1, 'le')" type=button value=C name=Button>
   dernier roman de Daniel Pennac?<br>
   2. Ce soir, je vais dîner chez 
   <input 
      size=9 name=item2>
   <input onClick="dasher(form.item2, 'les')" type=button value=C name=Button>
   voisins d'à côté.<br>
   3. 
   <input size=9 name=item3>
   <input onClick="dasher(form.item3, 'La')" type=button value=C name=Button>
   nouvelle femme de Jean-Luc, elle est italienne?<br>
   4. 
   <input size=9 
      name=item4>
   <input onClick="dasher(form.item4, 'Les')" type=button value=C name=Button>
   fils de ma soeur habitent à Paris. <br>
   5. J'adore 
   <input size=9 
      name=item5>
   <input onClick="dasher(form.item5, 'les')" type=button value=C name=Button>
   beaux bijoux.<br>
   6. Comment s'appelle 
   <input size=9 name=item6>
   <input onClick="dasher(form.item6, 'la')" type=button value=C name=Button>
   nouvelle prof d'espagnol?<br>
   7. Il habite 
   <input size=9 name=item7>
   <input onClick="dasher(form.item7, 'la')" type=button value=C name=Button>
   grande maison en face de la poste.<br>
   8. Je n'aime pas 
   <input size=9 
      name=item8>
   <input onClick="dasher(form.item8, 'les')" type=button value=C name=Button>
   cheveux roux.<br>
   9. J'attends 
   <input size=9 name=item9>
   <input onClick="dasher(form.item9, 'les')" type=button value=C name=Button>
   examens avec impatience. <br>
   10. 
   <input size=9 name=item10>
   <input onClick="dasher(form.item10, 'Le')" type=button value=C name=Button>
   fils de Sylvie est mécanicien. <br>
   <br>
   <br>
   <input onClick="form.item1.value='le';form.item2.value='les';form.item3.value='La';form.item4.value='Les';form.item5.value='les';form.item6.value='la';form.item7.value='la';form.item8.value='les';form.item9.value='les';form.item10.value='Le';" type=button value="Réponses" name=Button>
   <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';form.item9.value='';form.item10.value='';" type=button value="Effacer" name=Button>
   </font> 
</form>

<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>