---
title: "Days of the week"
---

<p align=left><font face="Garamond" size="4">Complétez en utilisant les 
        jours de la semaine (lundi, mardi, etc).<br>
        Cliquez "C" --&gt; correction.<br>
        Correct? --&gt; *astérisques*. <br>
        Incorrect?--&gt; =.<br>
        </font></p>

 <form action="" method=post>
              <font face="Garamond" size="4">1. Les Chrétiens vont à la messe 
              le 
              <input 
      size=9 name=item1>
              <input onClick="dasher(form.item1, 'dimanche')" type=button value=C name=Button>
              .<br>
              2. Le jour saint pour les Musulmans, c'est le 
              <input size=9 name=item2>
              <input onClick="dasher(form.item2, 'vendredi')" type=button value=C name=Button>
              .<br>
              3. Les Juifs vont au temple le 
              <input size=9 name=item3>
              <input onClick="dasher(form.item3, 'samedi')" type=button value=C name=Button>
              .<br>
              4.En France, les enfants ne vont pas à l'école le 
              <input size=9 name=item4>
              <input onClick="dasher(form.item4, 'mercredi')" type=button value=C name=Button>
              et le dimanche, mais certaines écoles ont des cours le 
              <input size=9 
      name=item5>
              <input onClick="dasher(form.item5, 'samedi')" type=button value=C name=Button>
              matin. <br>
              5. 
              <input size=9 name=item6>
              <input onClick="dasher(form.item6, 'Lundi')" type=button value=C name=Button>
              , c'est le premier jour de la semaine du travail. <br>
              6. La fête du ''Thanksgiving'' aux États-Unis, c'est toujours un 
              <input size=9 
      name=item7>
              <input onClick="dasher(form.item7, 'jeudi')" type=button value=C name=Button>
              .<br>
              7. En France, les musées sont souvent fermés le 
              <input size=9 name=item8>
              <input onClick="dasher(form.item8, 'mardi')" type=button value=C name=Button>
              . <br>
              <br>
              <br>
              <input onClick="form.item1.value='dimanche';form.item2.value='vendredi';form.item3.value='samedi';form.item4.value='mercredi';form.item5.value='samedi';form.item6.value='Lundi';form.item7.value='jeudi';form.item8.value='mardi';" type=button value="Réponses" name=Button>
              <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';" type=button value="Effacer" name=Button>
              </font> 
            </form>
<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>