---
title: "In/at/to a place"
---

<p align=left><font face="Garamond" size="4">Complétez en utilisant "en," 
        "au," "à," ou "aux." <br>
        Cliquez "C" --&gt; correction.<br>
        Correct? --&gt; *astérisques*. <br>
        Incorrect?--&gt; =.</font><font face="Garamond" size="4"><br>
        </font> </p>

<form action="" method=post>
              <font face="Garamond" size="4"> 1. Cet été, je passe mes vacances 
              <input 
      size=9 name=item1>
              <input onClick="dasher(form.item1, 'aux')" type=button value=C name=Button>
              Etats-Unis.<br>
              2. Nous pensons voyager 
              <input size=9 name=item2>
              <input onClick="dasher(form.item2, 'en')" type=button value=C name=Button>
              France à Noël.<br>
              3. Mon frère a fait du jonglage 
              <input size=9 
name=item3>
              <input onClick="dasher(form.item3, 'au')" type=button value=C name=Button>
              Vietnam.<br>
              4. Nous avons un nouveau contrat 
              <input size=9 name=item4>
              <input onClick="dasher(form.item4, 'en')" type=button value=C name=Button>
              Indonésie.<br>
              5. Mon oncle habite 
              <input size=9 name=item5>
              <input onClick="dasher(form.item5, 'en')" type=button value=C name=Button>
              Turquie.<br>
              6. Elle vit 
              <input size=9 name=item6>
              <input onClick="dasher(form.item6, 'au')" type=button value=C name=Button>
              Mexique.<br>
              7. Nous allons 
              <input size=9 name=item7>
              <input onClick="dasher(form.item7, 'en')" type=button value=C name=Button>
              Hollande bientôt.<br>
              8. Les conditions 
              <input size=9 name=item8>
              <input onClick="dasher(form.item8, 'en')" type=button value=C name=Button>
              Irak sont difficiles.<br>
              9. Mon meilleur ami habite 
              <input size=9 
      name=item9>
              <input onClick="dasher(form.item9, 'à')" type=button value=C name=Button>
              Paris.<br>
              10. Il va travailler 
              <input size=9 name=item10>
              <input onClick="dasher(form.item10, 'au')" type=button value=C name=Button>
              Japon.<br>
              11. J'aimerais habiter 
              <input size=9 name=item11>
              <input onClick="dasher(form.item11, 'à')" type=button value=C name=Button>
              Honolulu. <br>
              <br>
              <input onClick="form.item1.value='aux';form.item2.value='en';form.item3.value='au';form.item4.value='en';form.item5.value='en';form.item6.value='au';form.item7.value='en';form.item8.value='en';form.item9.value='à';form.item10.value='au';form.item11.value='à';" type=button value="Réponses" name=Button>
              <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';form.item9.value='';form.item10.value='';form.item11.value='';" type=button value="Effacer" name=Button>
              </font> 
            </form>

<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>
