---
title: Révision - la durée
---
## SINCE

- **depuis + présent:** J'habite ici depuis mardi dernier (quelque chose qui continue au présent)
- **depuis + passé composé au négatif:** Je n'ai pas mangé depuis hier (quelque chose qui continue à ne pas exister au présent)
- **depuis + l’imparfait:** Je travaillais depuis onze heures. (I had been working since eleven o'clock.)

## FOR

- **depuis (ça fait…que, il y a...que) + présent:** J'habite ici depuis 2 ans (qqch qui continue au présent)
- **depuis (ça fait…que, il y a...que) + passé composé (négatif):** Je n'ai pas mangé depuis 2 jours. (quelque chose qui continue à ne pas exister au présent)
- **pendant + passé composé:** J'ai travaillé à Colby pendant 5 mois. (quelque chose du passé qui n'existe plus)
- **pour + futur (or implied future) (être, verbes de mouvement):** Je pars pour un an, et après on verra.
- **pendant + future (or implied future) (autres verbes):** Je vais étudier l'arabe pendant trois mois avant de partir en Irak.

## AGO

- **il y a + passé composé:** Je suis arrivée à Colby il y a 7 mois.

## IN

- **en + passé composé, présent, futur (=length of time to do sthg):** J'ai terminé mes devoirs en 1 heure.
- **dans + futur (= how long from now sthg will start):** Je vais commencer mes devoirs dans une heure.
