---
title: Le plus-que-parfait
---

## Exemples

- Marie a appelé pour me demander d’aller au ciné, mais j’avais déjà vu le film.
- Nous étions toujours allés à Vale pour skier, mais Valentin voulait aller à Aspen l’année dernière.
- J’avais faim parce que je n’avais rien mangé de la journée.

## Le plus-que-parfait

1. Pour parler d’un événement du passé AVANT un autre événement du passé

### Exemples

- Je serais devenue folle si j’avais passé un jour de plus avec Marc.
- Si les digues à la Nouvelle Orléans avaient tenu, l’ouragan n’aurait pas détruit la ville.
- Si George Allen n’avait pas fait un commentaire raciste, il n’aurait pas perdu l’élection.

## Le plus-que-parfait

1. Pour parler d’un événement du passé AVANT un autre événement du passé
2. "Si" + plus-que-parfait --> conditionnel passé

- Plus ou moins comme "HAD DONE" en anglais,
- Mais:
  - Quand il s’agit de "HAD BEEN DOING" (action progressive du passé interrompue par une autre action); on utilise IMPARFAIT + depuis
  - Je travaillais à Colby depuis 3 ans quand je suis partie.
  - Je connaissais Marc depuis 5 ans quand j’ai découvert qu’il était un tueur en série.
  - J’avais mes perroquets depuis 15 ans quand j’ai appris que les perroquets sont capables de parler.

## Le plus-que-parfait: formation

- Imparfait de l’auxiliaire (avoir ou être) + participe passé
- J’avais fait
- J’étais monté

## Pratique: complétez les phrases pour exprimer vos regrets.

- Que regrettez-vous de votre temps au lycée?
  - Si j’avais passé plus de temps avec mes amis…
  - Si j’avais étudié un peu plus…
  - Si j’avais joué au football…
  - Si j’avais fait…
  - Si j’étais allé(e)…
