---
title: Relative Pronouns in French
toc: false
---

# Relative Pronouns: les pronoms relatifs

Relative pronouns are used to combine sentences and to avoid redundancy in writing. They introduce relative clauses, which describe, define, or expand on something already referred to in the sentence. In English, the relative pronouns are usually "who," "whom," "which," or "that."

- I need the book <span style="color: blue;">**which** is in your bag</span>.
- Julie is a person <span style="color: blue;">**whom** I hold in the highest esteem.
- What is the title of the paper to <span style="color: blue;">**which** you referred earlier?

In each of these sentences, the relative pronoun is in **bold**, and <span style="color: blue;">the relative clause is in blue (the rest of the sentence could stand alone without it).

In English, we often omit the relative pronoun (Julie is a person I hold in the highest esteem.), but in French, you must always use it.

To choose the correct relative pronoun in French, you need to ask two questions:

1. What is the grammatical function of the pronoun in the relative clause?
2. Are we referring to a person or a thing?

Let's ask these questions for our example sentences.

- I need the book <span style="color: blue;">**which** is in your bag.</span>
Look at the realtive clause -- 
  - Is "which" the subject of the verb "is," its object, or the object of a preposition?
  - Does "which" refer to a person or a thing?

Likewise, in this example:

- Julie is a person <span style="color: blue;">**whom** I hold in the highest esteem.</span>
Look at the realtive clause -- 
  - Is "whom" the subject of the verb "hold," its object, or the object of a preposition?
  - Does "whom" refer to a person or a thing?

Try this one:

- What is the title of the paper to <span style="color: blue;">**which** you referred earlier?</span>
Look at the realtive clause -- 
  - Is "which" the subject of the verb "referred," its object, or the object of a preposition?
  - Does "which" refer to a person or a thing?

Once you've figured out the answers to these two questions, this chart shows which relative pronoun to choose in each case.

## Relative Pronouns in French

| Grammatical Function of Relative Pronoun in Sentence | Refers to Person | Refers to Thing | Means "What" (has no specific antecedent) | Example Sentences in French |
| --------------------------------------------------- | --------------- | --------------- | ---------------------------------------- | ---------------------------- |
| Subject of Sentence                                  | qui             | qui             | ce qui                                 | Dans ce film, il y a un homme qui adore sa femme. Dans ce film, il y a une bombe qui explose en ville. Je ne sais pas ce qui est dans le carton. |
| Direct Object of Sentence                            | que             | que             | ce que                                 | Michelle est la personne que je préfère. Où sont les devoirs que tu as faits hier soir? Ce que j'adore, c'est la pizza aux oignons. |
| Object of Preposition: à, sur, avec, etc.            | à qui           | auquel (see note), sur lequel, avec lequel, etc.  | ce à quoi, ce sur quoi, ce avec quoi, etc...[FREN 201s don't need this] | La personne à qui je parle est mon prof de français. La chaise sur laquelle tu es assis est fragile. -- |
| Object of Preposition: de                           | dont            | dont            | ce dont                                | La femme dont je suis amoureuse est ici. L'argent dont j'ai besoin est ici. Je ne sais pas ce dont tu as peur. |
| Object of Complex Preposition: à côté de, près de, loin de, en face de, etc. | à côté duquel,** près duquel,** loin duquel,** etc.  | à côté duquel,** près duquel,** loin duquel,** etc.  | --                                      | La femme près de laquelle j'habite est gentille. J'aime bien le bar à côté duquel il y a un jardin. -- |
| Time Expression (le jour, l'année, etc.) = Means "When" or Place Expression = Means "Where" | --              | où              | --                                      | Le jour où je suis née, mon frère a eu une crise. -- |

**Auquel is a contraction of à + lequel.
Duquel is a contraction of de + lequel.
When the pronoun refers to a feminine or a plural, lequel becomes laquelle, lesquels, or lesquelles, and no contraction is made, so you get à laquelle, de laquelle, etc.
