---
title: "Writing ordinals (premier, deuxième, etc)"
---
<p align=left><font face="Garamond" size="4">Complétez les phrases par un 
        chiffre ordinal (premier, deuxième, troisième, etc.)<br>
        Cliquez "C" --&gt; correction.<br>
        Correct? --&gt; *astérisques*. <br>
        Incorrect?--&gt; ====.</font></p>

 <form action="" method=post>
              <font face="Garamond" size="4"> Septembre est le 
              <input size=15 name=item1>
              <input onClick="dasher(form.item1, 'neuvième')" type=button value=C name=Button>
              mois de l'année.<br>
              La 
              <input size=15 name=item2>
              <input onClick="dasher(form.item2, 'cinquième')" type=button value=C name=Button>
              symphonie de Beethoven est la plus célèbre.<br>
              Le paradis s'appelle parfois &quot;le 
              <input size=15 name=item3>
              <input onClick="dasher(form.item3, 'septième')" type=button value=C name=Button>
              ciel.&quot;<br>
              Souvent, &quot;Maman&quot; est le 
              <input size=15 name=item4>
              <input onClick="dasher(form.item4, 'premier')" type=button value=C name=Button>
              mot que les bébés prononcent.<br>
              Non, merci, j'ai pris 9 livres, je n'ai pas besoin d'un 
              <input size=15 name=item5>
              <input onClick="dasher(form.item5, 'dixième')" type=button value=C name=Button>
              .<br>
              La fête de l'indépendance des Etats-Unis, c'est le 
              <input size=15 name=item6>
              <input onClick="dasher(form.item6, 'quatrième')" type=button value=C name=Button>
              jour du mois de juillet.<br>
              Il y a un film américain célèbre, avec Bruce Willis, qui s'appelle 
              &quot;Le 
              <input size=15 name=item7>
              <input onClick="dasher(form.item7, 'sixième')" type=button value=C name=Button>
              sens.&quot;<br>
              Tu veux une 
              <input size=15 name=item8>
              <input onClick="dasher(form.item8, 'deuxième')" type=button value=C name=Button>
              chance?<br>
              H est la 
              <input size=15 name=item9>
              <input onClick="dasher(form.item9, 'huitième')" type=button value=C name=Button>
              lettre de notre alphabet.<br>
              Mars est le 
              <input size=15 name=item10>
              <input onClick="dasher(form.item10, 'troisième')" type=button value=C name=Button>
              mois de l'année.<br>
              <br>
              <br>
              <br>
              <input onClick="form.item1.value='neuvième';form.item2.value='cinquième';form.item3.value='septième';form.item4.value='premier';form.item5.value='dixième';form.item6.value='quatrième';form.item7.value='sixième';form.item8.value='deuxième';form.item9.value='huitième';form.item10.value='troisième';" type=button value="Réponses" name=Button>
              <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';form.item9.value='';form.item10.value='';" type=button value="Effacer" name=Button>
              </font> 
            </form>

<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>