---
title: "Writing 1-100 (1)"
---
<p align=left><font face="Garamond" size="4">Écrivez les nombres suivants, 
        en utilisant des chiffres.<br>
        Cliquez "C" --&gt; correction.<br>
        Correct? --&gt; *astérisques*. <br>
        Incorrect?--&gt; ====.<br>
        </font></p>


<form action="" method=post>
              <font face="Garamond" size="4"> trente-six 
              <input size=7 name=item1>
              <input onClick="dasher(form.item1, '36')" type=button value=C name=Button>
              <br>
              soixante-dix-huit 
              <input size=7 name=item2>
              <input onClick="dasher(form.item2, '78')" type=button value=C name=Button>
              <br>
              cinquante-neuf 
              <input size=7 name=item3>
              <input onClick="dasher(form.item3, '59')" type=button value=C name=Button>
              <br>
              soixante-dix 
              <input size=7 name=item4>
              <input onClick="dasher(form.item4, '70')" type=button value=C name=Button>
              <br>
              soixante-deux 
              <input size=7 name=item5>
              <input onClick="dasher(form.item5, '62')" type=button value=C name=Button>
              <br>
              quatre-vingt-deux 
              <input size=7 name=item6>
              <input onClick="dasher(form.item6, '82')" type=button value=C name=Button>
              <br>
              quatre-vingt-douze 
              <input size=7 name=item7>
              <input onClick="dasher(form.item7, '92')" type=button value=C name=Button>
              <br>
              quatre-vingt-dix 
              <input size=7 name=item8>
              <input onClick="dasher(form.item8, '90')" type=button value=C name=Button>
              <br>
              quatre-vingt-dix-huit 
              <input size=7 name=item9>
              <input onClick="dasher(form.item9, '98')" type=button value=C name=Button>
              <br>
              vingt-cinq 
              <input size=7 name=item10>
              <input onClick="dasher(form.item10, '25')" type=button value=C name=Button>
              <br>
              quatre-vingt-cinq 
              <input size=7 name=item11>
              <input onClick="dasher(form.item11, '85')" type=button value=C name=Button>
              <br>
              seize 
              <input size=7 name=item12>
              <input onClick="dasher(form.item12, '16')" type=button value=C name=Button>
              <br>
              dix 
              <input size=7 name=item13>
              <input onClick="dasher(form.item13, '10')" type=button value=C name=Button>
              <br>
              deux 
              <input size=7 name=item14>
              <input onClick="dasher(form.item14, '2')" type=button value=C name=Button>
              <br>
              <br>
              <br>
              <input onClick="form.item1.value='36';form.item2.value='78';form.item3.value='59';form.item4.value='70';form.item5.value='62';form.item6.value='82';form.item7.value='92';form.item8.value='90';form.item9.value='98';form.item10.value='25';form.item11.value='85';form.item12.value='16';form.item13.value='10';form.item14.value='2';" type=button value="Réponses" name=Button>
              <input onClick="form.item1.value='';form.item2.value='';form.item3.value='';form.item4.value='';form.item5.value='';form.item6.value='';form.item7.value='';form.item8.value='';form.item9.value='';form.item10.value='';form.item11.value='';form.item12.value='';form.item13.value='';form.item14.value='';" type=button value="Effacer" name=Button>
              </font> 
            </form>

<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>