---
title: "Telling Time (3)"
---

<form action="" method=POST name=a>
   <center>
      <table border=0 cellpadding=6 width=100%>
         <tr>
            <td>
               <center>
                  <font face="Garamond" size="4"><b>Quelle heure est-il?</b> 
                  </font> 
                  <p align=left><font face="Garamond" size="4">Indiquez l'heure 
                     dans la colonne de gauche qui correspond à l'heure dans 
                     la colonne de droite.</font>
                  </p>
                  <font face="Garamond" size="4"><br>
                  <br>
                  </font> 
                  <table width=90%>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=0 value="" size=1 maxlength=1>
                           1. 12h </font>
                        </td>
                        <td><font face="Garamond" size="4"> a. deux heures vingt-cinq 
                           </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=1 value="" size=1 maxlength=1>
                           2. 8h30 </font>
                        </td>
                        <td><font face="Garamond" size="4"> b. une heure de l'après-midi 
                           </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           3. 13h </font>
                        </td>
                        <td><font face="Garamond" size="4"> c. neuf heures du 
                           soir </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           4. 9h45 </font>
                        </td>
                        <td><font face="Garamond" size="4"> d. huit heures et 
                           demie </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           5. 21h </font>
                        </td>
                        <td><font face="Garamond" size="4"> e. huit heures et 
                           quart </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           6. 9h </font>
                        </td>
                        <td><font face="Garamond" size="4"> f. midi </font></td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           7. 23h50 </font>
                        </td>
                        <td><font face="Garamond" size="4"> g. dix heures moins 
                           le quart </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           8. 14h30 </font>
                        </td>
                        <td><font face="Garamond" size="4"> h. seize heures </font></td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           9. 16h </font>
                        </td>
                        <td><font face="Garamond" size="4"> i. neuf heures du 
                           matin </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           10. 8h15 </font>
                        </td>
                        <td><font face="Garamond" size="4"> j. deux heures et 
                           demie de l'après-midi </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           11. 14h25 </font>
                        </td>
                        <td><font face="Garamond" size="4"> k. minuit moins dix 
                           </font>
                        </td>
                     </tr>
                  </table>
               </center>
         </tr>
      </table>
   </center>
</form>
<center>
<form action="" method=POST name=e>
   <center>
      <font face="Garamond" size="4"> 
      <input type=button name=Button value="Correction" onClick="f()">
      </font> 
   </center>
</form>
<form action="" method=POST name=incor>
   <font face="Garamond" size="4"> 
   <input type=hidden name=wrong value="">
   </font> 
</form>

<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu, 
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>
<script language="JavaScript">
var c = 0
b=new Array(12)
b[0]='f';
b[1]='d';
b[2]='b';
b[3]='g';
b[4]='c';
b[5]='i';
b[6]='k';
b[7]='j';
b[8]='h';
b[9]='e';
b[10]='a';
b[11]='';
function f(){
var x = 0
ISWrong = 0
for (x=0; x<(document.a.elements.length); x++){
   if(document.a.elements[x].value!=""){
   document.a.elements[x].value = document.a.elements[x].value.toLowerCase()
   }
	if ((document.a.elements[x].value == b[x]) || (document.a.elements[x].value == b[x].toLowerCase())){
		}
	else {
		ISWrong = 1;
   if(document.a.elements[x].value!=""){
   z=x+1
  document.incor.wrong.value = document.incor.wrong.value+document.a.elements[x].value+" ne correspond pas à "+z+".  ";
  	}
		document.a.elements[x].value = '';
		}	
	}
if (ISWrong == 1) {
	Feedback = "Bien, mais il y a encore quelques erreurs."+" "+ document.incor.wrong.value;
 document.incor.wrong.value="";
	}
else {
	Feedback = "100%! Bravo!"
	}
alert(Feedback)
}</script>