---
title: "Telling Time (5)"
---

<form action="" method=POST name=a>
   <center>
      <table border=0 cellpadding=6 width=100%>
         <tr>
            <td>
               <center>
                  <font face="Garamond" size="4"><b>Quelle heure est-il en France?</b> 
                  </font> 
                  <p align=left><font face="Garamond" size="4">Voici la journ&eacute;e 
                     de Marine, &eacute;tudiante &agrave; la fac d'Aix-en-Provence. 
                     Elle se l&egrave;ve &agrave; sept heures et elle prend son 
                     petit d&eacute;jeuner: du pain, du beurre, et du caf&eacute; 
                     au lait. &Agrave; huit heures, elle prend le bus pour aller 
                     &agrave; la fac, car son premier cours commence &agrave; 
                     neuf heures. Entre midi et une heure et demie, elle est 
                     libre pour d&eacute;jeuner avec ses amis &agrave; la caf&eacute;t&eacute;ria. 
                     Mais son apr&egrave;s-midi est charg&eacute;; elle n'a qu'une 
                     demie-heure de libre avant cinq heures. &Agrave; six heures, 
                     elle a l'habitude de rencontrer ses amis au caf&eacute; 
                     pour prendre un verre et discuter, puis, elle rentre &agrave; 
                     la maison vers sept heures du soir, car sa famille d&icirc;ne 
                     ensemble &agrave; sept heures et demie. Elle aime regarder 
                     le journal t&eacute;l&eacute;vis&eacute; avec ses parents 
                     &agrave; huit heures tous les soirs, puis elle &eacute;tudie 
                     avant de se coucher vers onze heures du soir.</font>
                  </p>
                  <p align=left><font face="Garamond" size="4">Choisissez l'heure, 
                     à droite, qui correspond à la situation, à gauche.</font><font face="Garamond" size="4"><br>
                     </font> 
                  </p>
                  <table width=90%>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=0 value="" size=1 maxlength=1>
                           1. Marine prend son caf&eacute;.</font>
                        </td>
                        <td><font face="Garamond" size="4"> a. Il est six heures 
                           du soir. </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=1 value="" size=1 maxlength=1>
                           2. Marine d&icirc;ne en famille. </font>
                        </td>
                        <td><font face="Garamond" size="4"> b. Il est sept heures 
                           du matin. </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           3. Martine se r&eacute;veille. </font>
                        </td>
                        <td><font face="Garamond" size="4"> c. Il est 8h. </font></td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           4. Martine prend un verre au caf&eacute;.</font>
                        </td>
                        <td><font face="Garamond" size="4"> d. Il est vingt heures. 
                           </font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           5. Martine prend son bus.</font>
                        </td>
                        <td><font face="Garamond" size="4"> e. Il est sept heures 
                           et quart du matin.</font>
                        </td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           6. Le journal t&eacute;l&eacute;vis&eacute; que les 
                           parents de Martine regardent commence.</font>
                        </td>
                        <td><font face="Garamond" size="4"> f. Il est 14h30. </font></td>
                     </tr>
                     <tr>
                        <td> <font face="Garamond" size="4"> 
                           <input type=text name=2 value="" size=1 maxlength=1>
                           7. Martine est en cours. </font>
                        </td>
                        <td><font face="Garamond" size="4"> g. Il est sept heures 
                           et demie du soir. </font>
                        </td>
                     </tr>
                  </table>
               </center>
         </tr>
      </table>
   </center>
</form>
<center>
<form action="" method=POST name=e>
   <center>
      <font face="Garamond" size="4"> 
      <input type=button name=Button value="Correction" onClick="f()">
      </font> 
   </center>
</form>
<form action="" method=POST name=incor>
   <font face="Garamond" size="4"> 
   <input type=hidden name=wrong value="">
   </font> 
</form>

<SCRIPT Language="JavaScript">
//  This code is based on George Mitrevski's original CLOZE code.  
//  Dennie Hoopingarner modified it to provide more detailed feedback about the user's responses, 
//  in a manner similar to the Dasher program.
//  You are welcome to use and modify this code, but please give credit where credit is due. 
//  Dennie Hoopingarner, Michigan State University  hooping4@msu.edu
//  Content by: Alison Murray Levine, University of Virginia, alevine@virginia.edu
function dasher(Student, Correct) {
var studentAnswer = Student.value;
var correctAnswer = Correct;
result = ""
for (var c = 0; c< correctAnswer.length; c ++) {
	var CorrectX = correctAnswer.charAt(c);
	var StudentX = studentAnswer.charAt(c);
	if (CorrectX == StudentX) {
	result = result + CorrectX;
	}
	else {
	result = result +  "=";
	}
}
Student.value = result;
    if (studentAnswer == correctAnswer){
    Student.value = "*" + studentAnswer + "*";
    }
}

<!-- done hiding --></SCRIPT>
<script language="JavaScript">
var c = 0
b=new Array(12)
b[0]='e';
b[1]='g';
b[2]='b';
b[3]='a';
b[4]='c';
b[5]='d';
b[6]='f';
b[7]='';
b[8]='';
b[9]='';
b[10]='';
b[11]='';
function f(){
var x = 0
ISWrong = 0
for (x=0; x<(document.a.elements.length); x++){
   if(document.a.elements[x].value!=""){
   document.a.elements[x].value = document.a.elements[x].value.toLowerCase()
   }
	if ((document.a.elements[x].value == b[x]) || (document.a.elements[x].value == b[x].toLowerCase())){
		}
	else {
		ISWrong = 1;
   if(document.a.elements[x].value!=""){
   z=x+1
  document.incor.wrong.value = document.incor.wrong.value+document.a.elements[x].value+" ne correspond pas à "+z+".  ";
  	}
		document.a.elements[x].value = '';
		}	
	}
if (ISWrong == 1) {
	Feedback = "Bien, mais il y a encore quelques erreurs."+" "+ document.incor.wrong.value;
 document.incor.wrong.value="";
	}
else {
	Feedback = "100%! Bravo!"
	}
alert(Feedback)
}</script>